### ISSUE TITLE
User service: Add Route for GetFilteredUserInfo

### ISSUE THREAD

**Issue by PradyumnaShome** [HackIllinois/api#48] opened 2018-09-02 07:44 UTC
Controller function at: https://github.com/HackIllinois/api/blob/5ef2301fc16447a435c84176a6105e4acd532aae/services/user/controller/controller.go#L67

Location of proposed Route: https://github.com/HackIllinois/api/blob/5ef2301fc16447a435c84176a6105e4acd532aae/gateway/services/user.go#L34

This should be restricted to `Admin`s.

**Comment by ASankaran** [comment] 2018-09-03 04:11
Duplicate of #24

**Closed by ASankaran** 2018-09-03 04:11 UTC
Labels: Bug, Gateway, User
